#!/bin/bash

# Based on a script by a man named Andrew
# Originally located at http://blog.theinternets.be/rpi-munin-temperatures/

if [ "$1" == "autoconf" ]; then
     if [ -e /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq ]; then
         echo "yes"
     else
         echo "no"
         exit 1
     fi
elif [ "$1" == "config" ]; then
     echo "graph_title Raspberry Pi Frequency"
     echo "graph_args --base 1000 -l 0"
     echo "graph_vlabel Frequency in MHz"
     echo "graph_category Sensors"
     echo "cpu.label CPU"
else
     echo "cpu.value $(( $(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq)/1000 ))"
fi
