#!/bin/bash

# Based on a script by a man named Andrew
# Originally located at http://blog.theinternets.be/rpi-munin-temperatures/
# Don't forget to load kernel modules: w1-gpio w1-therm
# Change OneWire device address

if [ "$1" == "autoconf" ]; then
     if [ -e /sys/devices/w1_bus_master1/w1_master_slaves ]; then
         echo "yes"
     else
         echo "no"
         exit 1
     fi
elif [ "$1" == "config" ]; then
     echo "graph_title Raspberry Pi OneWire Temperature"
     echo "graph_args --base 1000 -l 0"
     echo "graph_vlabel Temperature in Celsius"
     echo "graph_category Sensors"
     echo "temp.warning 30"
     echo "temp.critical 40"
     echo "temp.label OneWire"
else 
     w1_slave=$(cat /sys/devices/w1_bus_master1/w1_master_slaves)
     temp=$(tail -1 /sys/bus/w1/devices/$w1_slave/w1_slave | cut -d ' ' -f 10-11 | sed 's/[^=]*=//' )
     awk "BEGIN { print \"temp.value \" $temp/1000 }"
fi
