#!/bin/bash

# Based on a script by a man named Andrew
# Originally located at http://blog.theinternets.be/rpi-munin-temperatures/
# Don't forget to load kernel modules: w1-gpio w1-therm
# Change OneWire device address

if [ "$1" == "autoconf" ]; then
     if [ -e /usr/bin/local/Adafruit:DHT ]; then
         echo "yes"
     else
         echo "no"
         exit 1
     fi
elif [ "$1" == "config" ]; then
     echo "graph_title Raspberry DHT Sensor"
     echo "graph_category Sensors"
     echo "temp.label "
        I=$((I+1));
     done
else
	I=1;
	for w1_slave in $(cat /sys/devices/w1_bus_master1/w1_master_slaves)
	do
	     temp=$(tail -1 /sys/bus/w1/devices/$w1_slave/w1_slave | cut -d ' ' -f 10-11 | sed 's/[^=]*=//' )
	     awk "BEGIN { printf \"temp$I.value %2.3f\n\", $temp/1000 }"
	     I=$(($I+1));
	done
fi
